/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.connect.DBConnect;
import Model_Product.Thuoctinh.ChatLieu;
import Model_Product.Thuoctinh.LoaiCoCao;
import Model_Product.Thuoctinh.MauSac;
import Model_Product.Thuoctinh.Size;
import Model_Product.Thuoctinh.ThuongHieu;
import Model_Product.Repository_Thuoctinh.ChatLieuRepository;
import Model_Product.Repository_Thuoctinh.LoaiCoCaoRepository;
import Model_Product.Repository_Thuoctinh.MauSacRepository;
import Model_Product.Repository_Thuoctinh.SizeRepository;
import Model_Product.Repository_Thuoctinh.ThuongHieuRepository;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVEN
 */
public class AttributesProduct extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    Connection connection = DBConnect.getConnection();
    private final DefaultTableModel model = new DefaultTableModel();
    private final MauSacRepository rp = new MauSacRepository(connection);
    private final SizeRepository rp1 = new SizeRepository(connection);
    private final ChatLieuRepository rp2 = new ChatLieuRepository(connection);
    private final ThuongHieuRepository rp3 = new ThuongHieuRepository(connection);
    private final LoaiCoCaoRepository rp4 = new LoaiCoCaoRepository(connection);

    public AttributesProduct() {
        initComponents();
        model.setColumnIdentifiers(new Object[]{"ID", "Tên", "Mô tả"});
        TblTT.setModel(model);
    }

    void fillTableMauSac() {
        try {
            List<MauSac> mauSacs = rp.getAllMauSacs();
            model.setRowCount(0);

            for (MauSac mauSac : mauSacs) {
                model.addRow(new Object[]{mauSac.getId(), mauSac.getTen(), mauSac.getMoTa()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTableSize() {
        try {
            List<Size> sizes = rp1.getAllSizes();
            model.setRowCount(0);

            for (Size size : sizes) {
                model.addRow(new Object[]{size.getId(), size.getTen(), size.getMoTa()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTableChatLieu() {
        try {
            List<ChatLieu> chatLieus = rp2.getAllChatLieus();
            model.setRowCount(0);

            for (ChatLieu chatLieu : chatLieus) {
                model.addRow(new Object[]{chatLieu.getId(), chatLieu.getTen(), chatLieu.getMoTa()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTableThuongHieu() {
        try {
            List<ThuongHieu> thuongHieus = rp3.getAllThuongHieus();
            model.setRowCount(0);

            for (ThuongHieu thuongHieu : thuongHieus) {
                model.addRow(new Object[]{thuongHieu.getId(), thuongHieu.getTen(), thuongHieu.getMoTa()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTableLoaiCoCao() {
        try {
            List<LoaiCoCao> coAoList = rp4.getAllLoaiCoCaos();
            model.setRowCount(0);

            for (LoaiCoCao coAo : coAoList) {
                model.addRow(new Object[]{coAo.getId(), coAo.getTen(), coAo.getMoTa()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTaTT = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        rdo_size = new javax.swing.JRadioButton();
        rdo_chatlieu = new javax.swing.JRadioButton();
        rdo_thuonghieu = new javax.swing.JRadioButton();
        rdo_mausac = new javax.swing.JRadioButton();
        rdo_loaicocao = new javax.swing.JRadioButton();
        txt_tenTT = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTT = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin thuộc tính sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã thuộc tính:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên thuộc tính:");

        txtMaTT.setEditable(false);
        txtMaTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mô tả:");

        txtMoTaTT.setColumns(20);
        txtMoTaTT.setRows(5);
        jScrollPane2.setViewportView(txtMoTaTT);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Loại thuộc tính:");

        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Sua.setText("Update");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdo_size);
        rdo_size.setText("Size");
        rdo_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_sizeActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdo_chatlieu);
        rdo_chatlieu.setText("Chất liệu");
        rdo_chatlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_chatlieuActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdo_thuonghieu);
        rdo_thuonghieu.setText("Thương hiệu");
        rdo_thuonghieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_thuonghieuActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdo_mausac);
        rdo_mausac.setText("Màu sắc");
        rdo_mausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_mausacActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdo_loaicocao);
        rdo_loaicocao.setText("Cổ áo");
        rdo_loaicocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_loaicocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(rdo_mausac)
                        .addGap(7, 7, 7)
                        .addComponent(rdo_size)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_chatlieu)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_thuonghieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_loaicocao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenTT)
                            .addComponent(txtMaTT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Them)
                        .addGap(34, 34, 34)
                        .addComponent(Sua)
                        .addGap(33, 33, 33)
                        .addComponent(Xoa))
                    .addComponent(jScrollPane2))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Xoa)
                            .addComponent(Sua)
                            .addComponent(Them))
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_size)
                            .addComponent(rdo_chatlieu)
                            .addComponent(rdo_thuonghieu)
                            .addComponent(rdo_mausac)
                            .addComponent(rdo_loaicocao))
                        .addGap(3, 3, 3)))
                .addGap(25, 25, 25))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Danh sách thuộc tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        TblTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã thuộc tính", "Tên thuộc tính", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblTTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblTT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 920, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TblTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblTTMouseClicked

        int row = TblTT.getSelectedRow();

        if (row != -1) {

            int id = (int) TblTT.getValueAt(row, 0);
            String ten = (String) TblTT.getValueAt(row, 1);
            String moTa = (String) TblTT.getValueAt(row, 2);

            txtMaTT.setText(String.valueOf(id));
            txt_tenTT.setText(ten);
            txtMoTaTT.setText(moTa);
        }

    }//GEN-LAST:event_TblTTMouseClicked


    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        try {
            if (rdo_mausac.isSelected()) {
                MauSac mauSac = new MauSac(0, txt_tenTT.getText(), txtMoTaTT.getText());
                rp.addMauSac(mauSac);
                fillTableMauSac();
            } else if (rdo_size.isSelected()) {
                Size size = new Size(0, txt_tenTT.getText(), txtMoTaTT.getText());
                rp1.addSize(size);
                fillTableSize();
            } else if (rdo_chatlieu.isSelected()) {
                ChatLieu chatLieu = new ChatLieu(0, txt_tenTT.getText(), txtMoTaTT.getText());
                rp2.addChatLieu(chatLieu);
                fillTableChatLieu();
            } else if (rdo_thuonghieu.isSelected()) {
                ThuongHieu thuongHieu = new ThuongHieu(0, txt_tenTT.getText(), txtMoTaTT.getText());
                rp3.addThuongHieu(thuongHieu);
                fillTableThuongHieu();
            } else if (rdo_loaicocao.isSelected()) {
                LoaiCoCao coAo = new LoaiCoCao(0, txt_tenTT.getText(), txtMoTaTT.getText());
                rp4.addLoaiCoCao(coAo);
                fillTableLoaiCoCao();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        try {
            if (rdo_mausac.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                rp.deleteMauSac(id);
                fillTableMauSac();
            } else if (rdo_size.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                rp1.deleteSize(id);
                fillTableSize();
            } else if (rdo_chatlieu.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                rp2.deleteChatLieu(id);
                fillTableChatLieu();
            } else if (rdo_thuonghieu.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                rp3.deleteThuongHieu(id);
                fillTableThuongHieu();
            } else if (rdo_loaicocao.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                rp4.deleteLoaiCoCao(id);
                fillTableLoaiCoCao();
            }
        } catch (SQLException e) {
            if (e.getErrorCode() == 547) {
                JOptionPane.showMessageDialog(this, " thuộc tính này đang được sử dụng ", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_XoaActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        try {
            if (rdo_mausac.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                MauSac mauSac = new MauSac(id, txt_tenTT.getText(), txtMoTaTT.getText());
                rp.updateMauSac(mauSac);
                fillTableMauSac();
            } else if (rdo_size.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                Size size = new Size(id, txt_tenTT.getText(), txtMoTaTT.getText());
                rp1.updateSize(size);
                fillTableSize();
            } else if (rdo_chatlieu.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                ChatLieu chatLieu = new ChatLieu(id, txt_tenTT.getText(), txtMoTaTT.getText());
                rp2.updateChatLieu(chatLieu);
                fillTableChatLieu();
            } else if (rdo_thuonghieu.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                ThuongHieu thuongHieu = new ThuongHieu(id, txt_tenTT.getText(), txtMoTaTT.getText());
                rp3.updateThuongHieu(thuongHieu);
                fillTableThuongHieu();
            } else if (rdo_loaicocao.isSelected()) {
                int id = Integer.parseInt(txtMaTT.getText());
                LoaiCoCao coAo = new LoaiCoCao(id, txt_tenTT.getText(), txtMoTaTT.getText());
                rp4.updateLoaiCoCao(coAo);
                fillTableLoaiCoCao();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SuaActionPerformed

    private void rdo_loaicocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_loaicocaoActionPerformed
        // TODO add your handling code here:
        fillTableLoaiCoCao();
    }//GEN-LAST:event_rdo_loaicocaoActionPerformed

    private void rdo_mausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_mausacActionPerformed
        // TODO add your handling code here:
        if (rdo_mausac.isSelected()) {
            fillTableMauSac();
        }
    }//GEN-LAST:event_rdo_mausacActionPerformed

    private void rdo_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_sizeActionPerformed
        // TODO add your handling code here:
        fillTableSize();
    }//GEN-LAST:event_rdo_sizeActionPerformed

    private void rdo_chatlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_chatlieuActionPerformed
        // TODO add your handling code here:
        fillTableChatLieu();
    }//GEN-LAST:event_rdo_chatlieuActionPerformed

    private void rdo_thuonghieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_thuonghieuActionPerformed
        // TODO add your handling code here:
        fillTableThuongHieu();

    }//GEN-LAST:event_rdo_thuonghieuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sua;
    private javax.swing.JTable TblTT;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_chatlieu;
    private javax.swing.JRadioButton rdo_loaicocao;
    private javax.swing.JRadioButton rdo_mausac;
    private javax.swing.JRadioButton rdo_size;
    private javax.swing.JRadioButton rdo_thuonghieu;
    private javax.swing.JTextField txtMaTT;
    private javax.swing.JTextArea txtMoTaTT;
    private javax.swing.JTextField txt_tenTT;
    // End of variables declaration//GEN-END:variables
}
