/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Model_Product.DetailSanPham;
import Model_Product.Thuoctinh.ChatLieu;
import Model_Product.Thuoctinh.LoaiCoCao;
import Model_Product.Thuoctinh.MauSac;
import Model_Product.Thuoctinh.Size;
import Model_Product.Thuoctinh.ThuongHieu;
import Repository_Product.Repository_Detail;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class DetailProduct extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    private Repository_Detail rp = new Repository_Detail();
    private DefaultTableModel model = new DefaultTableModel();
    private int i = -1;
    private HashMap<String, Integer> colorMap = new HashMap<>();
    private HashMap<String, Integer> sizeMap = new HashMap<>();
    private HashMap<String, Integer> chatLieuMap = new HashMap<>();
    private HashMap<String, Integer> thuongHieuMap = new HashMap<>();
    private HashMap<String, Integer> loaiCoCaoMap = new HashMap<>();

    public DetailProduct() {
        initComponents();
        this.fillTable(rp.getAll());
        fillComboBoxMauSac();
        fillComboBoxSize();
        fillComboBoxChatLieu();
        fillComboBoxThuongHieu();
        fillComboBoxLoaiCoCao();
        /////////////////////
        ArrayList<MauSac> colors = rp.getAllMauSac();
        for (MauSac color : colors) {
            colorMap.put(color.getTen(), color.getId());
        }
        ArrayList<Size> sizes = rp.getAllSize();
        for (Size size : sizes) {
            sizeMap.put(size.getTen(), size.getId());
        }

        ArrayList<ChatLieu> chatLieus = rp.getAllChatLieu();
        for (ChatLieu chatLieu : chatLieus) {
            chatLieuMap.put(chatLieu.getTen(), chatLieu.getId());
        }

        ArrayList<ThuongHieu> thuongHieus = rp.getAllThuongHieu();
        for (ThuongHieu thuongHieu : thuongHieus) {
            thuongHieuMap.put(thuongHieu.getTen(), thuongHieu.getId());
        }

        ArrayList<LoaiCoCao> loaiCoCaos = rp.getAllLoaiCoCao();
        for (LoaiCoCao loaiCoCao : loaiCoCaos) {
            loaiCoCaoMap.put(loaiCoCao.getTen(), loaiCoCao.getId());
        }
        rp.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals("dataChanged")) {
                    new SwingWorker<Void, Void>() {
                        @Override
                        protected Void doInBackground() throws Exception {
                            fillTable(rp.getAll());
                            return null;
                        }

                        @Override
                        protected void done() {

                        }
                    }.execute();
                }
            }
        });
    }

    void fillTable(ArrayList<DetailSanPham> list) {
        model = (DefaultTableModel) tblSPCT.getModel();
        model.setRowCount(0);

        for (DetailSanPham sp : list) {
            model.addRow(sp.toDataRow2());
        }
    }

    /////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDSPCT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaCTSP = new javax.swing.JTextArea();
        cboMauSac = new javax.swing.JComboBox<>();
        cboSize = new javax.swing.JComboBox<>();
        cboChatLieu = new javax.swing.JComboBox<>();
        cboThuongHieu = new javax.swing.JComboBox<>();
        txtTenSP = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        cboLoaiCoCao = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSPCT = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboFilterTrangThai = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cboFilterChatLieu = new javax.swing.JComboBox<>();
        cboFilterThuongHieu = new javax.swing.JComboBox<>();
        cboFilterKichThuoc = new javax.swing.JComboBox<>();
        cboFilterMauSac = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID SPCT");

        txtIDSPCT.setEditable(false);
        txtIDSPCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSPCTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Giá bán(VNĐ)");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng tồn");
        jLabel4.setToolTipText("");

        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Màu sắc");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Size");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Chất liệu");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Thương hiệu");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mô tả");

        txtMoTaCTSP.setColumns(20);
        txtMoTaCTSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMoTaCTSP.setRows(5);
        jScrollPane1.setViewportView(txtMoTaCTSP);

        cboMauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMauSacActionPerformed(evt);
            }
        });

        cboSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSizeActionPerformed(evt);
            }
        });

        cboChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChatLieuActionPerformed(evt);
            }
        });

        cboThuongHieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã SP");

        txtMaSP.setEditable(false);
        txtMaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        cboLoaiCoCao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoaiCoCao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Loại cổ áo");

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtTenSP))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIDSPCT, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboMauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboChatLieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_them)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sua)
                                .addGap(18, 18, 18)
                                .addComponent(btn_xoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnrefresh)
                                .addGap(0, 4, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboLoaiCoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(cboLoaiCoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua)
                            .addComponent(btn_them)
                            .addComponent(btn_xoa)
                            .addComponent(btnrefresh)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblSPCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Sản phẩm", "Tên SP", "Màu sắc", "Size", "Chất liệu", "Thương hiệu", "Loại cổ áo", "Giá bán", "Số lượng", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPCTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSPCTMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tblSPCT);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tìm kiếm");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Trạng thái");

        cboFilterTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboFilterTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Còn hàng", "Hết hàng" }));
        cboFilterTrangThai.setToolTipText("");
        cboFilterTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterTrangThaiActionPerformed(evt);
            }
        });

        jPanel3.setLayout(null);

        cboFilterChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboFilterChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFilterChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterChatLieuActionPerformed(evt);
            }
        });
        jPanel3.add(cboFilterChatLieu);
        cboFilterChatLieu.setBounds(195, 9, 33, 26);

        cboFilterThuongHieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboFilterThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFilterThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterThuongHieuActionPerformed(evt);
            }
        });
        jPanel3.add(cboFilterThuongHieu);
        cboFilterThuongHieu.setBounds(155, 9, 22, 26);

        cboFilterKichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboFilterKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFilterKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterKichThuocActionPerformed(evt);
            }
        });
        jPanel3.add(cboFilterKichThuoc);
        cboFilterKichThuoc.setBounds(103, 9, 34, 26);

        cboFilterMauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboFilterMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFilterMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterMauSacActionPerformed(evt);
            }
        });
        jPanel3.add(cboFilterMauSac);
        cboFilterMauSac.setBounds(42, 9, 28, 26);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)))
                        .addComponent(cboFilterTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(cboFilterTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSPCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSPCTActionPerformed

    private void cboMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMauSacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMauSacActionPerformed

    private void cboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSizeActionPerformed

    private void cboChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChatLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChatLieuActionPerformed

    private void tblSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPCTMouseClicked
        int selectedRow = tblSPCT.getSelectedRow();

        if (selectedRow >= 0) {
            String id = tblSPCT.getValueAt(selectedRow, 0).toString();
            String idSanPham = tblSPCT.getValueAt(selectedRow, 1).toString();
            String tenSanPham = tblSPCT.getValueAt(selectedRow, 2).toString();
            String mauSac = tblSPCT.getValueAt(selectedRow, 3) != null ? tblSPCT.getValueAt(selectedRow, 3).toString() : "";
            String size = tblSPCT.getValueAt(selectedRow, 4) != null ? tblSPCT.getValueAt(selectedRow, 4).toString() : "";
            String chatLieu = tblSPCT.getValueAt(selectedRow, 5) != null ? tblSPCT.getValueAt(selectedRow, 5).toString() : "";
            String thuongHieu = tblSPCT.getValueAt(selectedRow, 6) != null ? tblSPCT.getValueAt(selectedRow, 6).toString() : "";
            String loaiCoCao = tblSPCT.getValueAt(selectedRow, 7) != null ? tblSPCT.getValueAt(selectedRow, 7).toString() : "";
            String giaBan = tblSPCT.getValueAt(selectedRow, 8).toString();
            String soLuongTon = tblSPCT.getValueAt(selectedRow, 9).toString();
            String moTa = tblSPCT.getValueAt(selectedRow, 10) != null ? tblSPCT.getValueAt(selectedRow, 10).toString() : "";

            txtIDSPCT.setText(id);
            txtMaSP.setText(idSanPham);
            txtTenSP.setText(tenSanPham);
            txtGiaBan.setText(giaBan);
            txtSoLuong.setText(soLuongTon);
            txtMoTaCTSP.setText(moTa);

            cboMauSac.setSelectedItem(mauSac.isEmpty() ? cboMauSac.getItemAt(0) : mauSac);
            cboSize.setSelectedItem(size.isEmpty() ? cboSize.getItemAt(0) : size);
            cboChatLieu.setSelectedItem(chatLieu.isEmpty() ? cboChatLieu.getItemAt(0) : chatLieu);
            cboThuongHieu.setSelectedItem(thuongHieu.isEmpty() ? cboThuongHieu.getItemAt(0) : thuongHieu);
            cboLoaiCoCao.setSelectedItem(loaiCoCao.isEmpty() ? cboLoaiCoCao.getItemAt(0) : loaiCoCao);
        }
    }//GEN-LAST:event_tblSPCTMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String keyword = txtTimKiem.getText().trim();
        ArrayList<DetailSanPham> filteredDetailProducts = rp.searchDetailProductsByKeyword(keyword);
        fillTable(filteredDetailProducts);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void cboFilterChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterChatLieuActionPerformed

    }//GEN-LAST:event_cboFilterChatLieuActionPerformed

    private void cboFilterThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterThuongHieuActionPerformed

    }//GEN-LAST:event_cboFilterThuongHieuActionPerformed

    private void cboFilterTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterTrangThaiActionPerformed
        String selectedTrangThai = (String) cboFilterTrangThai.getSelectedItem();
        ArrayList<DetailSanPham> filteredProducts;

        switch (selectedTrangThai.toLowerCase()) {
            case "tất cả":
                filteredProducts = rp.getAll();
                break;
            case "còn hàng":
                filteredProducts = rp.getDetailProductsByTrangThai(true);
                break;
            case "hết hàng":
                filteredProducts = rp.getDetailProductsByTrangThai(false);
                break;
            default:
                filteredProducts = new ArrayList<>();
                break;
        }
        fillTable(filteredProducts);
    }//GEN-LAST:event_cboFilterTrangThaiActionPerformed

    private void cboFilterKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterKichThuocActionPerformed

    }//GEN-LAST:event_cboFilterKichThuocActionPerformed

    private void cboFilterMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterMauSacActionPerformed

    }//GEN-LAST:event_cboFilterMauSacActionPerformed

    private void tblSPCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPCTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSPCTMouseEntered

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        if (isValidDetailProductData()) {
            try {
                String tenSanPham = txtTenSP.getText();
                String idSanPham = txtMaSP.getText();
                String moTa = txtMoTaCTSP.getText();

                int idMauSac = colorMap.get(cboMauSac.getSelectedItem().toString());
                int idSize = sizeMap.get(cboSize.getSelectedItem().toString());
                int idChatLieu = chatLieuMap.get(cboChatLieu.getSelectedItem().toString());
                int idThuongHieu = thuongHieuMap.get(cboThuongHieu.getSelectedItem().toString());
                int idLoaiCoCao = loaiCoCaoMap.get(cboLoaiCoCao.getSelectedItem().toString());

                BigDecimal giaBan = new BigDecimal(txtGiaBan.getText());
                int soLuongTon = Integer.parseInt(txtSoLuong.getText());

                DetailSanPham detailSanPham = new DetailSanPham(
                        null, idSanPham, tenSanPham, idMauSac, idSize, idChatLieu,
                        idThuongHieu, idLoaiCoCao, giaBan, soLuongTon, moTa
                );

                if (rp.addDetailProduct(detailSanPham)) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm chi tiết thành công!");
                    fillTable(rp.getAll());
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm chi tiết thất bại!");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Giá bán và số lượng tồn phải là số!");
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ thông tin!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed
    private void clearForm() {
        txtIDSPCT.setText("");
        txtTenSP.setText("");
        txtMaSP.setText("");
        txtMoTaCTSP.setText("");
        txtGiaBan.setText("");
        txtSoLuong.setText("");
    }
    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        String idToDelete = txtIDSPCT.getText();

        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa sản phẩm chi tiết này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (rp.deleteDetailProduct(idToDelete)) {
                    JOptionPane.showMessageDialog(null, "Xóa sản phẩm chi tiết thành công!");
                    this.fillTable(rp.getAll());
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa sản phẩm chi tiết thất bại!");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        if (isValidDetailProductData()) {
            try {
                String id = txtIDSPCT.getText();

                String tenSanPham = txtTenSP.getText();
                String idSanPham = txtMaSP.getText();
                String moTa = txtMoTaCTSP.getText();

                int idMauSac = colorMap.get(cboMauSac.getSelectedItem().toString());
                int idSize = sizeMap.get(cboSize.getSelectedItem().toString());
                int idChatLieu = chatLieuMap.get(cboChatLieu.getSelectedItem().toString());
                int idThuongHieu = thuongHieuMap.get(cboThuongHieu.getSelectedItem().toString());
                int idLoaiCoCao = loaiCoCaoMap.get(cboLoaiCoCao.getSelectedItem().toString());

                BigDecimal giaBan = new BigDecimal(txtGiaBan.getText());
                int soLuongTon = Integer.parseInt(txtSoLuong.getText());

                DetailSanPham detailSanPham = new DetailSanPham(
                        id, idSanPham, tenSanPham, idMauSac, idSize, idChatLieu,
                        idThuongHieu, idLoaiCoCao, giaBan, soLuongTon, moTa
                );

                if (rp.updateDetailProduct(detailSanPham)) {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm chi tiết thành công!");
                    fillTable(rp.getAll());
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm chi tiết thất bại!");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Giá bán và số lượng tồn phải là số!");
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ thông tin!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:    
        this.fillTable(rp.getAll());
        fillComboBoxMauSac();
        fillComboBoxSize();
        fillComboBoxChatLieu();
        fillComboBoxThuongHieu();
        fillComboBoxLoaiCoCao();
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JComboBox<String> cboChatLieu;
    private javax.swing.JComboBox<String> cboFilterChatLieu;
    private javax.swing.JComboBox<String> cboFilterKichThuoc;
    private javax.swing.JComboBox<String> cboFilterMauSac;
    private javax.swing.JComboBox<String> cboFilterThuongHieu;
    private javax.swing.JComboBox<String> cboFilterTrangThai;
    private javax.swing.JComboBox<String> cboLoaiCoCao;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblSPCT;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtIDSPCT;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextArea txtMoTaCTSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
private void fillComboBoxMauSac() {
        cboMauSac.removeAllItems();
        ArrayList<MauSac> colors = rp.getAllMauSac();

        for (MauSac color : colors) {
            cboMauSac.addItem(color.getTen());
        }
    }

    private void fillComboBoxSize() {
        cboSize.removeAllItems();
        ArrayList<Size> sizes = rp.getAllSize();

        for (Size size : sizes) {
            cboSize.addItem(size.getTen());
        }
    }

    private void fillComboBoxChatLieu() {
        cboChatLieu.removeAllItems();
        ArrayList<ChatLieu> chatLieus = rp.getAllChatLieu();

        for (ChatLieu chatLieu : chatLieus) {
            cboChatLieu.addItem(chatLieu.getTen());
        }
    }

    private void fillComboBoxThuongHieu() {
        cboThuongHieu.removeAllItems();
        ArrayList<ThuongHieu> thuongHieus = rp.getAllThuongHieu();

        for (ThuongHieu thuongHieu : thuongHieus) {
            cboThuongHieu.addItem(thuongHieu.getTen());
        }
    }

    private void fillComboBoxLoaiCoCao() {
        cboLoaiCoCao.removeAllItems();
        ArrayList<LoaiCoCao> loaiCoCaos = rp.getAllLoaiCoCao();

        for (LoaiCoCao loaiCoCao : loaiCoCaos) {
            cboLoaiCoCao.addItem(loaiCoCao.getTen());
        }
    }

    private boolean isValidDetailProductData() {
        if (txtTenSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống.");
            return false;
        }

        try {
            BigDecimal giaBan = new BigDecimal(txtGiaBan.getText());
            if (giaBan.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0.");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá bán không hợp lệ.");
            return false;
        }

        try {
            int soLuongTon = Integer.parseInt(txtSoLuong.getText());
            if (soLuongTon < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng tồn phải lớn hơn hoặc bằng 0.");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng tồn không hợp lệ.");
            return false;
        }

        if (cboMauSac.getSelectedIndex() == -1 || cboSize.getSelectedIndex() == -1
                || cboChatLieu.getSelectedIndex() == -1 || cboThuongHieu.getSelectedIndex() == -1
                || cboLoaiCoCao.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ thông tin thuộc tính.");
            return false;
        }

        return true;
    }
}
